# Generated by Django 4.2.7 on 2025-10-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragsession',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the RAG session', null=True),
        ),
    ]
