# Generated by Django 4.2.7 on 2025-10-15 16:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0002_ragsession_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='chunk_count',
            field=models.IntegerField(default=0, help_text='Number of chunks created from this document'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('txt', 'Text'), ('pdf', 'PDF'), ('docx', 'Word Document')], default='txt', max_length=10),
        ),
        migrations.AddField(
            model_name='ragsession',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions to guide the RAG agent behavior', null=True),
        ),
        migrations.CreateModel(
            name='ChunkMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='The actual chunk content')),
                ('summary', models.TextField(blank=True, help_text='Summary of the chunk content', null=True)),
                ('question', models.TextField(blank=True, help_text='Generated question for this chunk', null=True)),
                ('answer', models.TextField(blank=True, help_text='Generated answer for the question', null=True)),
                ('chunk_index', models.IntegerField(help_text='Index of this chunk in the document')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for the chunk')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag_api.document')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
